spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    schema: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: com.trae.loganalysis.config.SQLiteDialect
    properties:
      hibernate:
        dialect: com.trae.loganalysis.config.SQLiteDialect
        jdbc:
          use_get_generated_keys: false
        query:
          pagination:
            limit-handler: sqlite
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 激活的配置文件
spring.profiles.active: dev