# 开发环境配置
spring:
  datasource:
    url: jdbc:sqlite:./log_analysis.db?journal_mode=WAL
    username: sa
    password: sa
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2KB
      location: ./tmp

# 服务器配置
server:
  port: 8080

# 文件配置
file:
  upload:
    path: ./uploads/
  analysis:
    thread-pool-size: 5

# API配置
api:
  log-analysis:
    url: http://localhost:8080/logAnalysis/api/itoa/ck/getLogInfo
    system-code: NCB
    condition:
      key: LEVEL
      value: ERROR
    size: 10
  ai-suggestion:
    url: http://localhost:8080/logai/analysis/ai/suggestion
    system-code: NCB
    query-params:
      data-set-id: 1232
      center-ids: [4343]
      app-id: 2343
      index-prefix: index
      size: 100
      remark: downContext

# 日志配置
logging:
  level:
    com.trae: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR